### PR TITLE
SPM support

### PR DESCRIPTION
**Pull request by rromanchuk**

### CODE REVIEW

**Comment by Nirma** [comment]
@rromanchuk Nice, anytime you are ready to have the review I am happy to check it out. 

Looks good so far, is there another reason why its still in "draft"?

**Comment by fredpi** [comment]
Would be great to get SPM support soon!

**Comment by Nirma** [comment]
@rromanchuk I hope you don't mind that Im going to go ahead and merge this. The reason being that I'm renaming the old `master` branch to `main` and don't want to waste your time asking you to target a new branch.

**Comment by Nirma** [comment]
@fredpi I am implementing this right now! I deeply apologize for the wait, expect a release with SPM support in a few hours.

**Comment by fredpi** [comment]
> @fredpi I am implementing this right now! I deeply apologize for the wait, expect a release with SPM support in a few hours. 

Thank you very much, @Nirma!

**Comment by rromanchuk** [comment]
@Nirma oops sorry, I just started using it for testing and forgot i even made a PR. Thanks! Switching back to `Nirma/Attributed` before i forget, again.

**Pull request merged**
